version: 2.1
orbs:
  node: circleci/node@4.7

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Install and Run BDD tests
          command: |
            npm install cucumber
            npm run test:bdd

workflows:
  build-and-test:
    jobs:
      - build-and-test
